### ISSUE TITLE
과제 질문

### ISSUE THREAD

**Issue by xoxojw** [xoxojw/ts-to-do-list#7]
### 1. 진행 중/완료 상태 toggle 관련
```tsx
// ListTodos.tsx
import { useSelector, useDispatch } from "react-redux";
// ...
const handleToggle = (e: React.MouseEvent<HTMLButtonElement>, id: string) => {
    e.preventDefault();
    dispatch(toggleTodo(id));
}
```
```tsx
// todoSlice.ts
const todoSlice = createSlice({
  name: "todosReducer",
  initialState,
  reducers: {
    // ... 생략
    toggleTodo: (state, action) => {
      const todo = state.todos.find(todo => todo.id === action.payload);
      if (todo) {
        todo.isDone = !todo.isDone;
    },
  }
})
```
처음에는 위와 같이 진행 중/완료 상태변경을 button의 handleToggle 함수로 단순하게 구현을 완료 했었는데요.
진행 중/완료 상태 변경을 button이 아닌, `<input type="checkbox />`로 수정했더니 isDone의 상태와 checked의 상태가 같이 가지 않더라고요. (checkbox의 checked 속성이 boolean이라 isDone과 싱크가 잘 맞을줄 알았는데..)

현재 어찌저찌 수정해 놓은 코드는 아래와 같은데, 아래의 방법처럼 index를 찾아서 toogleTodo 리듀서 함수를 작성해야만 할까요? 다른 방법이 있는지 궁금합니다!
```tsx
// ListTodos.tsx
import { useSelector, useDispatch } from "react-redux";

// ...

const handleToggle = (e: React.ChangeEvent<HTMLInputElement>, id: string) => {
    dispatch(toggleTodo({id, isDone: e.target.checked}));
};

// ...

return (
  <>
    {sortedTodos.map((todo) => {
      return (
        <StTodoItem key={todo.id}>
          <StItemHeader>
            <StTodoTitle isDone={todo.isDone}>
            <input
              type="checkbox"
              checked={todo.isDone}
              onChange={(e) => handleToggle(e, todo.id)}
            />
              {todo.title}
            </StTodoTitle>
{ /* ...생략 */}
```
```tsx
// todoSlice.ts
toggleTodo: (state, action) => {
    const index = state.todos.findIndex(todo => todo.id === action.payload.id);
    if (index !== -1) {
      state.todos[index] = { ...state.todos[index], isDone: !state.todos[index].isDone };
    }
  },  
```

<br />

### 2. 컨벤션 관리
현재 저는 `src/common/global.d.ts` 폴더에 타입을 export하여 지정해놓고, 필요한 곳에서 꺼내썼는데
폴더명이나 파일명 컨벤션을 이런 식으로 작성하는게 맞는건지 잘 모르겠더라구요.😂

```ts
// global.d.ts
export type RootState = {
  todos: Todo[];
};

export type Todo = {
  id: string;
  title: string;
  content: string;
  isDone: boolean;
}
```
  ~~1) interface 대신 type으로 지정해줘도 큰 지장이 없는지~~
  2) type을 지정해준 전역 파일명을 global.d.ts로 작성해도 되는 것인지 궁금합니다.

<br />

감사합니다. 😊

<br />

**Comment by xoxojw** [comment]
Types vs. Interfaces
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/basic_type_example/

| Aspect                          | Type | Interface |
|---------------------------------|------|-----------|
| Can describe functions          | ✅   | ✅        |
| Can describe constructors       | ✅   | ✅        |
| Can describe tuples             | ✅   | ✅        |
| Interfaces can extend it        | ⚠️   | ✅        |
| Classes can extend it           | 🚫   | ✅        |
| Classes can implement it        | ⚠️   | ✅        |
| Can intersect another one of its kind | ✅ | ⚠️        |
| Can create a union with another one of its kind | ✅ | 🚫        |
| Can be used to create mapped types | ✅ | 🚫        |
| Can be mapped over with mapped types | ✅ | ✅        |
| Expands in error messages and logs | ✅ | 🚫        |
| Can be augmented                | 🚫   | ✅        |
| Can be recursive                | ⚠️   | ✅        |

**Comment by devsince2021** [comment]
1. 진행 중/완료 상태 toggle 관련
boolean 이란 타입을 공유하는 대상들끼리 호환이 자유로울 것이라는 접근이 아주 좋은 것 같습니다.
typescript를 잘 이해하고 계신다는 생각이듭니다~

동작이 안했던 것은 구현 중에 실수가 있으셨던 것이 아닐까합니다
다른 곳 변경없이 todoSlice만 아래와 같이 변경하니 토글이 잘 되는것 같습니다.

```
// todoSlice.ts
const todo = state.todos.find((todo) => todo.id === action.payload.id);

if (todo) {
  todo.isDone = action.payload.isDone;
}
```

**Comment by devsince2021** [comment]
2. 컨벤션 관리

현재 코드를 보았을 때, 사용되고 있는 타입이 많지 않고 의미상으로도 적절하게 보여서 global이라는 이름이 크게 어색하다고 느껴지지는 않습니다.
하지만 프로젝트의 규모가 커진다면 global이라는 이름으로 다양한 종류의 타입들을 담기보다는 보다 세분화된 이름으로 구분해주는 것이 좋을 것 같습니다.

또 common이라는 폴더 속에 넣어 두셨는데, common이란 네이밍은 마찬가지로 굉장히 포괄적인 의미의 이름입니다. 오히려 type이라는 이름으로 설정해줄 수도 있지 않을까 하는 저의 개인적인 견해도 전달드립니다.

끝으로 이런한 폴더 구조나 파일명은 앞으로 일하시게 될 프로젝트에 어느정도 정해진 가이드라인이 있을 것이라고 예상됩니다.
어떤 프로젝트에서는 지금 해주신 것처럼 global 레벨에서 타입을 관리할 수도 있고, 어떤 프로젝트는 좀 더 하위 레벨에서 따로 관리할 수도 있을 것 같습니다. 따라서 개인 프로젝트시에는 나름의 적절한 이유를 가지고 위치를 선정한다면 크게 문제가 되지 않을 것으로 보여집니다.

**Comment by xoxojw** [comment]
> 2. 컨벤션 관리
> 
> 현재 코드를 보았을 때, 사용되고 있는 타입이 많지 않고 의미상으로도 적절하게 보여서 global이라는 이름이 크게 어색하다고 느껴지지는 않습니다. 하지만 프로젝트의 규모가 커진다면 global이라는 이름으로 다양한 종류의 타입들을 담기보다는 보다 세분화된 이름으로 구분해주는 것이 좋을 것 같습니다.
> 
> 또 common이라는 폴더 속에 넣어 두셨는데, common이란 네이밍은 마찬가지로 굉장히 포괄적인 의미의 이름입니다. 오히려 type이라는 이름으로 설정해줄 수도 있지 않을까 하는 저의 개인적인 견해도 전달드립니다.
> 
> 끝으로 이런한 폴더 구조나 파일명은 앞으로 일하시게 될 프로젝트에 어느정도 정해진 가이드라인이 있을 것이라고 예상됩니다. 어떤 프로젝트에서는 지금 해주신 것처럼 global 레벨에서 타입을 관리할 수도 있고, 어떤 프로젝트는 좀 더 하위 레벨에서 따로 관리할 수도 있을 것 같습니다. 따라서 개인 프로젝트시에는 나름의 적절한 이유를 가지고 위치를 선정한다면 크게 문제가 되지 않을 것으로 보여집니다.

넵 지금 팀 과제 진행하면서는 type.ts 파일에 관리하고 있습니다! 피드백 감사드립니다~!
